# Generated by Django 5.1.7 on 2026-01-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedperson',
            name='department',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='trackedperson',
            name='email',
            field=models.EmailField(default='unknown@company.com', max_length=254),
        ),
        migrations.AddField(
            model_name='trackedperson',
            name='employee_id',
            field=models.CharField(default='EMP000', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='trackedperson',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trackedperson',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='trackedperson',
            name='role',
            field=models.CharField(default='Employee', max_length=50),
        ),
        migrations.AlterField(
            model_name='trackedperson',
            name='embedding_data',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='trackedperson',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
