# Generated by Django 5.1.7 on 2026-01-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_trackedperson_department_trackedperson_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('camera_id', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='Offline', max_length=20)),
                ('stream_url', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
