# Generated by Django 5.1.7 on 2026-05-22 17:50

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userprofile_face_embedding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trackedperson',
            name='classification',
            field=models.CharField(choices=[('known', 'Known'), ('unknown', 'Unknown'), ('blacklisted', 'Blacklisted')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='trackedperson',
            name='face_embedding',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='trackedperson',
            name='snapshot_image',
            field=models.ImageField(blank=True, null=True, upload_to='snapshots/'),
        ),
        migrations.AddField(
            model_name='violationlog',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.camera'),
        ),
        migrations.AddField(
            model_name='violationlog',
            name='snapshot_path',
            field=models.ImageField(blank=True, null=True, upload_to='violations/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='face_embedding',
            field=models.TextField(blank=True, null=True, validators=[api.models.validate_embedding_length]),
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('blacklist_type', models.CharField(choices=[('auto', 'Automatic'), ('manual', 'Manual')], default='auto', max_length=10)),
                ('violation_threshold', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_entries', to='api.trackedperson')),
            ],
        ),
    ]
