# Generated by Django 5.1.7 on 2026-05-23 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_camera_is_active_camera_last_heartbeat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedperson',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='trackedperson',
            name='semester',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='MovementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(max_length=100)),
                ('location_description', models.CharField(max_length=200)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('exited_at', models.DateTimeField(blank=True, null=True)),
                ('is_violation', models.BooleanField(default=False)),
                ('camera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.camera')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='api.trackedperson')),
            ],
            options={
                'ordering': ['-entered_at'],
            },
        ),
    ]
