# Generated by Django 5.1.7 on 2026-05-24 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_trackedperson_gender_trackedperson_semester_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('ssd', 'SSD'), ('department-head', 'Department Head'), ('guard', 'Guard')], max_length=20),
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=200)),
                ('host_name', models.CharField(max_length=100)),
                ('host_department', models.CharField(max_length=100)),
                ('check_in', models.DateTimeField(auto_now_add=True)),
                ('check_out', models.DateTimeField(blank=True, null=True)),
                ('expected_duration_hours', models.IntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('checked_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_logs', to='api.trackedperson')),
            ],
            options={
                'ordering': ['-check_in'],
            },
        ),
    ]
