# Generated by Django 5.1.7 on 2026-05-24 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_userprofile_role_visitorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='camera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.camera'),
        ),
        migrations.AddField(
            model_name='notification',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.trackedperson'),
        ),
        migrations.AddField(
            model_name='notification',
            name='violation_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.violationlog'),
        ),
    ]
