# Generated by Django 5.1.7 on 2026-05-30 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_notification_camera_notification_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='violation_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='api.violationlog'),
        ),
    ]
