# Generated by Django 5.1.7 on 2026-06-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_userprofile_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedperson',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
