# Generated by Django 5.1.7 on 2026-06-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_userprofile_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackedperson',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
