# Generated by Django 5.1.7 on 2026-06-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_trackedperson_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='DressCodeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing_class', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('compliant', 'Compliant'), ('violation', 'Violation'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('any', 'Any')], default='any', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['clothing_class'],
            },
        ),
    ]
