# Generated by Django 5.1.7 on 2026-06-18 19:32
#
# Seed DressCodeRule from the formerly-hardcoded sets in FinalSystem.py so behaviour is
# unchanged on day one. The original code only *used* VIOLATION_MALE / VIOLATION_FEMALE:
#     COMPLIANT_MALE   = {'m-button-down','m-formal-trousers','m-kurta','m-shalwar','m-shirts'}
#     COMPLIANT_FEMALE = {'w-dress','w-dupatta','w-eastern-trouser','w-kameez','w-shalwar'}
#     VIOLATION_MALE   = {'m-informal-pants','m-sleeveless'}
#     VIOLATION_FEMALE = {'w-western-shirt','w-western-trouser','m-sleeveless'}
#     NEUTRAL          = {'outerwear'}
# 'm-sleeveless' is a violation for BOTH genders, so it seeds as gender='any'. FinalSystem
# rebuilds the sets with gender in ('male','any') / ('female','any'), reproducing the above.

from django.db import migrations

# (clothing_class, status, gender)
SEED = [
    ('m-button-down',     'compliant', 'male'),
    ('m-formal-trousers', 'compliant', 'male'),
    ('m-kurta',           'compliant', 'male'),
    ('m-shalwar',         'compliant', 'male'),
    ('m-shirts',          'compliant', 'male'),
    ('m-informal-pants',  'violation', 'male'),
    ('m-sleeveless',      'violation', 'any'),   # violation for male AND female
    ('w-dress',           'compliant', 'female'),
    ('w-dupatta',         'compliant', 'female'),
    ('w-eastern-trouser', 'compliant', 'female'),
    ('w-kameez',          'compliant', 'female'),
    ('w-shalwar',         'compliant', 'female'),
    ('w-western-shirt',   'violation', 'female'),
    ('w-western-trouser', 'violation', 'female'),
    ('outerwear',         'neutral',   'any'),
]


def seed_rules(apps, schema_editor):
    DressCodeRule = apps.get_model('api', 'DressCodeRule')
    for clothing_class, status, gender in SEED:
        DressCodeRule.objects.update_or_create(
            clothing_class=clothing_class,
            defaults={'status': status, 'gender': gender},
        )


def unseed_rules(apps, schema_editor):
    DressCodeRule = apps.get_model('api', 'DressCodeRule')
    DressCodeRule.objects.filter(clothing_class__in=[c for c, _, _ in SEED]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_dresscoderule'),
    ]

    operations = [
        migrations.RunPython(seed_rules, unseed_rules),
    ]
