import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import fs from 'fs'
import { fileURLToPath } from 'url'

// HTTPS for LAN access: serve with the cert generated by certs/make_certs.ps1 (bound to the
// server's hostname so it survives IP changes). Falls back to plain HTTP if the certs aren't there.
const keyPath = fileURLToPath(new URL('../certs/server.key', import.meta.url))
const crtPath = fileURLToPath(new URL('../certs/server.crt', import.meta.url))
// HTTPS is opt-in (the launcher sets CODEWATCH_HTTPS=1) so the current HTTP launcher keeps working
// until the HTTPS-aware launcher ships.
const enableHttps = process.env.CODEWATCH_HTTPS === '1' && fs.existsSync(keyPath) && fs.existsSync(crtPath)
const httpsConfig = enableHttps
  ? { key: fs.readFileSync(keyPath), cert: fs.readFileSync(crtPath) }
  : undefined

export default defineConfig({
  plugins: [react()],
  server: {
    host: true,              // bind 0.0.0.0 so other devices on the LAN can connect
    https: httpsConfig,      // HTTPS when certs are present
    allowedHosts: true,      // accept the server's hostname (e.g. SMARNB / SMARNB.local) over the LAN
    proxy: {
      '/api': {
        target: 'http://127.0.0.1:8000',
        changeOrigin: true,
      },
      '/django-admin': {
        target: 'http://127.0.0.1:8000',
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\/django-admin/, '/admin'),
      },
      '/static': {
        target: 'http://127.0.0.1:8000',
        changeOrigin: true,
      },
      '/media': {
        target: 'http://127.0.0.1:8000',
        changeOrigin: true,
      }
    }
  }
})
