from django.contrib import admin
from django.urls import path
from api.views import (
    auth, people, dedup, cameras, violations, analytics, reports,
    notifications, tracking, blacklist, visitors, feedback, dress_code, search,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/admin/', admin.site.urls),
    path('api/register-unknown/', people.register_unknown),
    path('api/get-embeddings/', people.get_all_embeddings),
    path('api/log-violation/', violations.log_violation),
    path('api/activity/', analytics.get_recent_activity),
    path('api/stats/', analytics.get_violation_stats),
    path('api/people-db/', people.get_people_db),
    path('api/dashboard-stats/', analytics.get_dashboard_stats),
    path('api/add-member/', people.add_member),
    path('api/add-camera/', cameras.add_camera),
    path('api/test-camera-stream/', cameras.test_camera_stream),
    path('api/cameras/', cameras.get_cameras),
    path('api/camera-heartbeat/', cameras.camera_heartbeat),
    path('api/server-ip/', cameras.get_server_ip),
    path('api/cameras/<str:camera_id>/', cameras.manage_camera_detail),
    path('api/users/', auth.get_users),
    path('api/user-heartbeat/', auth.user_heartbeat),
    path('api/users/<int:user_id>/', auth.update_user_role),
    path('api/forgot-password/', auth.forgot_password),
    path('api/users/<int:user_id>/reset-password/', auth.reset_user_password),
    path('api/password-status/', auth.password_status),
    path('api/set-initial-password/', auth.set_initial_password),
    path('api/change-password/', auth.change_password),
    path('api/get-analytics/', analytics.get_analytics_data),
    path('api/analytics-filters/', analytics.get_analytics_filters),
    path('api/send-report/', reports.send_report),
    path('api/get-reports/', reports.get_reports),
    path('api/reports/<int:report_id>/', reports.get_report_detail),
    path('api/delete-report/<int:report_id>/', reports.delete_report),
    path('api/update-report/<int:report_id>/', reports.update_report),
    path('api/notifications/', notifications.get_notifications),
    path('api/notifications/read/<int:notif_id>/', notifications.mark_notif_read),
    path('api/notifications/read-all/', notifications.mark_all_notifications_read),
    path('api/notifications/clear/', notifications.clear_notifications),
    path('api/notifications/<int:pk>/', notifications.get_notification_detail),
    path('api/notifications/<int:pk>/violation-events/', notifications.get_violation_events),
    path('api/live-track/<int:person_id>/', tracking.get_live_tracking_feed),
    path('api/feedback/', feedback.submit_feedback),
    path('api/submit-feedback-report/', feedback.submit_feedback_report),
    path('api/violations/', violations.manage_violations),
    path('api/violations/<int:pk>/', violations.manage_violations),
    path('api/blacklist/', blacklist.manage_blacklist),
    path('api/blacklist/<int:pk>/', blacklist.manage_blacklist),
    path('api/blacklist/toggle/', blacklist.toggle_blacklist),
    path('api/people/<int:person_id>/classification/', people.set_person_classification),
    path('api/people/<int:person_id>/delete/', people.delete_person),
    path('api/people/<int:person_id>/add-photos/', people.add_person_photos),
    path('api/people/<int:person_id>/update-info/', people.update_person_info),
    path('api/login/', auth.login_view),
    path('api/movement-log/', tracking.log_movement),
    path('api/movement-history/<int:person_id>/', tracking.get_movement_history),
    path('api/live-track/start/', tracking.live_track_start),
    path('api/live-track/stop/', tracking.live_track_stop),
    path('api/search/', search.search_all),
    path('api/visitors/add/', visitors.add_visitor),
    path('api/visitors/active/', visitors.get_active_visitors),
    path('api/visitors/', visitors.get_all_visitors),
    path('api/visitors/checkout/<int:visitor_log_id>/', visitors.checkout_visitor),
    path('api/visitors/extend/<int:visitor_log_id>/', visitors.extend_visitor),
    path('api/dedup-identities/', dedup.dedup_identities),
    path('api/dress-code-rules/', dress_code.dress_code_rules),
    path('api/dress-code-rules/<int:pk>/', dress_code.update_dress_code_rule),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
